"""add party column to scanned_products

Revision ID: 3c8ccf16af5b
Revises: 9e023447b4d0
Create Date: 2026-07-13 16:57:02.053495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8ccf16af5b'
down_revision: Union[str, None] = '9e023447b4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scanned_products', sa.Column('party', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scanned_products', 'party')
    # ### end Alembic commands ###
