"""add new filed leminated in StickerGenerator class 8

Revision ID: 3ea0350c5ae0
Revises: 1fbc7451f9d4
Create Date: 2025-06-09 16:09:18.679886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ea0350c5ae0"
down_revision: Union[str, None] = "1fbc7451f9d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stickergenerator", sa.Column("leminated", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stickergenerator", "leminated")
    # ### end Alembic commands ###
