"""Add new filed in StickerGenerator table is_sold 6

Revision ID: 64774317e235
Revises: ea3bf4d54654
Create Date: 2025-06-08 16:13:29.092163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64774317e235'
down_revision: Union[str, None] = 'ea3bf4d54654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stickergenerator', sa.Column('is_sold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stickergenerator', 'is_sold')
    # ### end Alembic commands ###
