"""Add in user model Admin user and add colour table new filed is_white 4

Revision ID: 94bdc8c7c210
Revises: 5f3ebeffef69
Create Date: 2025-06-04 23:28:58.436266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94bdc8c7c210"
down_revision: Union[str, None] = "5f3ebeffef69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("colour", sa.Column("is_white", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("colour", "is_white")
    # ### end Alembic commands ###
