"""add party table and party_id to stickergenerator

Revision ID: 9e023447b4d0
Revises: fe7af5b64948
Create Date: 2026-07-13 11:22:56.954915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e023447b4d0'
down_revision: Union[str, None] = 'fe7af5b64948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_managers', 'gross_weight')
    op.drop_column('dispatch_managers', 'width')
    op.drop_column('dispatch_managers', 'gsm')
    op.drop_column('dispatch_managers', 'length')
    op.add_column('stickergenerator', sa.Column('party_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stickergenerator', 'party', ['party_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stickergenerator', type_='foreignkey')
    op.drop_column('stickergenerator', 'party_id')
    op.add_column('dispatch_managers', sa.Column('length', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('dispatch_managers', sa.Column('gsm', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('dispatch_managers', sa.Column('width', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('dispatch_managers', sa.Column('gross_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
