"""create ScannedProduct table

Revision ID: c03401e53e1e
Revises: ba0773041d2c
Create Date: 2025-06-03 22:12:36.582657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03401e53e1e'
down_revision: Union[str, None] = 'ba0773041d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanned_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_number', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('colour', sa.String(), nullable=True),
    sa.Column('net_weight', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanned_products_id'), 'scanned_products', ['id'], unique=False)
    op.create_index(op.f('ix_scanned_products_product_number'), 'scanned_products', ['product_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanned_products_product_number'), table_name='scanned_products')
    op.drop_index(op.f('ix_scanned_products_id'), table_name='scanned_products')
    op.drop_table('scanned_products')
    # ### end Alembic commands ###
