"""Added gross_weight field in ScannedProduct table 10

Revision ID: c06a36316f4e
Revises: da9ac805a6e7
Create Date: 2025-06-11 11:58:37.342069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06a36316f4e'
down_revision: Union[str, None] = 'da9ac805a6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scanned_products', sa.Column('gross_weight', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scanned_products', 'gross_weight')
    # ### end Alembic commands ###
