"""Added new field disptach_summary in DispatchManager table 9

Revision ID: da9ac805a6e7
Revises: 3ea0350c5ae0
Create Date: 2025-06-11 11:23:34.720926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9ac805a6e7'
down_revision: Union[str, None] = '3ea0350c5ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_managers', sa.Column('disptach_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_managers', 'disptach_summary')
    # ### end Alembic commands ###
