"""Again update that user role now its str 6

Revision ID: ea3bf4d54654
Revises: ef966770602f
Create Date: 2025-06-04 23:58:15.194979

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ea3bf4d54654"
down_revision: Union[str, None] = "ef966770602f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("STICKER_GUYS", "DISPATCH_GUYS", name="userrole"),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(),
        type_=postgresql.ENUM("STICKER_GUYS", "DISPATCH_GUYS", name="userrole"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
