"""grs_weight gsm length add in ScannedProduct or DispatchManager table 11

Revision ID: fe7af5b64948
Revises: c06a36316f4e
Create Date: 2025-06-12 16:45:34.245020

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe7af5b64948"
down_revision: Union[str, None] = "c06a36316f4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dispatch_managers",
        sa.Column("gross_weight", sa.DECIMAL(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "dispatch_managers", sa.Column("gsm", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "dispatch_managers",
        sa.Column("length", sa.DECIMAL(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "dispatch_managers",
        sa.Column("width", sa.DECIMAL(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "scanned_products", sa.Column("gsm", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "scanned_products",
        sa.Column("length", sa.DECIMAL(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "scanned_products",
        sa.Column("width", sa.DECIMAL(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanned_products", "width")
    op.drop_column("scanned_products", "length")
    op.drop_column("scanned_products", "gsm")
    op.drop_column("dispatch_managers", "width")
    op.drop_column("dispatch_managers", "length")
    op.drop_column("dispatch_managers", "gsm")
    op.drop_column("dispatch_managers", "gross_weight")
    # ### end Alembic commands ###
